$plugin = array(
  'title' => t('Follow Me: Github Connector'),
  'description' => t('Connect your Github Account'),
  'callback' => 'follow_me_github_ctools_access_check',
  'default' => array('field_age_value' => 0),
  'settings form' => 'follow_me_github_ctools_settings',
  'summary' => 'follow_me_github_ctools_summary',
);

function follow_me_github_ctools_access_check(){


}

function follow_me_github_ctools_settings(){


}

function follow_me_github_ctools_summary(){

}
