<?php

/**
 * Implementation of hook_menu().
 *
 * Provides a menu for selecting services to include
 * and entering a username for each.
 */

function follow_me_menu(){
  $items = array();
  $items['admin/config/services/follow_me'] = array(
    'title' => t('Follow Me'),
    'description' => t('Select and configure connected accounts'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('follow_me_accounts_config'),
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );
  return $items;
}

function follow_me_accounts_config() {
  $form = array();
  $form['#tree'] = TRUE;
  $form['follow_me_type'] = array(
    '#title' => t('Service Providers'),
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
  );
//@todo sloppy - still figuring out some things here
  ctools_include('plugins');
  $accounts = ctools_get_plugins('follow_me', 'follow_me_handler');
  foreach($accounts as $service) {
    $processed = call_user_func($service['callback']);
    $form['follow_me_type'][$service['name']] = array(
      'active' => $processed[$service['name']]['active'],
      'account' => $processed[$service['name']]['account'],
    );
  }

  return system_settings_form($form);
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function follow_me_ctools_plugin_api() {
  return array('version' => 1);
}

/**
 * Implementation of hook_ctools_plugin_type().
 */
function follow_me_ctools_plugin_type() {
  return array(
    'follow_me_handler' => array(),
  );
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function follow_me_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Return a list of all account handlers.
 */
function follow_me_handler_info() {
  ctools_include('plugins');

  static $handlers;
  if (!$handlers) {
    $handlers = ctools_get_plugins('follow_me', 'follow_me_handler');
  }
  return $handlers;
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function follow_me_form_follow_me_accounts_config_alter($form, &$form_state, $form_id){
  drupal_add_js(drupal_get_path('module', 'follow_me') .'/js/admin.js', 'file');
}

/**
 * Implementation of hook_block_info().
 */
function follow_me_block_info() {
  $blocks = array();
  $blocks['follow_me_block'] = array(
    'info' => t('Social Media Follow'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function follow_me_block_view($delta) {
  if ($delta == 'follow_me_block') {
    global $base_url;

    //get accounts that exist
    $user_accounts = variable_get('follow_me_type');

    ctools_include('plugins');
    $services = ctools_get_plugins('follow_me', 'follow_me_handler');

    $site_links = array();
    foreach ($user_accounts as $site => $data) {

      if (isset($data['active']) && $data['active'] == 1){
        $site_links[$site] = l('<img src="'. $base_url . '/' . drupal_get_path('module', 'follow_me') .'/images/'. $site . '.png" alt="'. $services[$site]['name'] .'" />',
          $services[$site]['url'] . $data['account'],
          array(
            'attributes' => array(
              'title' => 'Follow me on ' . $services[$site]['service name'],
              'target' => '_blank',
          ),
          'external' => TRUE,
          'html' => TRUE,
        ));
      }
    }

    //display config
    $style = 'display:inline';

    $args = array(
      'sites' => $site_links,
      'style' => $style,
    );
    $content = theme('follow_me_block', $args);
    $block = array(
      'subject' => '',
      'content' => $content,
    );
    return $block;
  }
}

/**
 * Implementation of hook_block_view().
 * @todo - move to render array
 */
function follow_me_theme() {
  return array(
    'follow_me_block' => array(
      'variables' => array($args = NULL),
      'template' => 'follow-me-block',
    ),
  );
}

