<?php

/**
 * Implementation of hook_menu.
 */

function follow_me_menu(){
  $items = array();
  $items['admin/config/follow_me'] = array(
    'title' => t('Follow Me'),
    'description' => t('Select and configure Social Media'),
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );
  $items['admin/config/follow_me/accounts'] = array(
    'title' => t('Configure Accounts'),
    'description' => t('Select and configure connected accounts'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('follow_me_accounts_config'),
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );

  return $items;

}

function follow_me_accounts_config() {
  $form = array();
  $form['#tree'] = TRUE;
  $form['follow_me_type'] = array(
    '#title' => t('Service Providers'),
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
  );
  $types = variable_get('follow_me_type', array());
  $form['follow_me_type']['github']['active'] = array(
    '#type' => 'checkbox',
    '#title' => t('Github'),
    '#default_value' => (($types['github']['active'] == 1) ? 1 : 0),

    '#description' => t("Enable Github?"),
    '#required' => FALSE,
  );
  $form['follow_me_type']['github']['account'] = array(
    '#type' => 'textfield',
    '#title' => t('Github'),
    '#default_value' => ((isset($types['github']['account']) == TRUE) ? $types['github']['account'] : NULL),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => t("Enter your Github user name"),
    '#required' => FALSE,
  );

  return system_settings_form($form);
}

/**
 * Follow Me Handler Information
 *
 * Return a list of all handlers that might connect an account.
 */
function follow_me_handler_info($field_type = NULL) {
  ctools_include('plugins');

  static $handlers;
  if (!$handlers) {
    $handlers = ctools_get_plugins('follow_me', 'follow_me_handler');
  }
  return $handlers;
}

/**
 * Fetch follow_me handler
 *
 * Given a name, fetch the full handler definition
 */
function follow_me_get_handler($handler_name) {
  $handlers = follow_me_handler_info();
  if (isset($handlers[$handler_name])) {
    return $handlers[$handler_name];
  }
  else return FALSE;
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function follow_me_ctools_plugin_api() {
  return array('version' => 1);
}

/**
 * Implementation of hook_ctools_plugin_dierctory() to let the system know
 * we implement plugins.
 */
function follow_me_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_ctools_plugin_type
 */
function follow_me_ctools_plugin_type() {
  return array(
    'follow_me_handler' => array(),
  );
}











/**
 * Implementation of hook_block_info.
 */
function follow_me_block_info() {
  $blocks = array();
  $blocks['follow_me_block'] = array(
    'info' => t('Social Media Follow'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view.
 */
function follow_me_block_view($delta) {
  if ($delta == 'follow_me_block') {
    global $base_url;

    $options = array(
      'twitter' => array(
        'name' => 'Twitter',
        'url' => 'http://twitter.com/#!/',
      ),
      'linkedin' => array(
        'name' => 'LinkedIn',
        'url' => 'http://www.linkedin.com/in/',
      ),
      'github' => array(
        'name' => 'GitHub',
        'url' => 'http://www.github.com/',
      ),
      'facebook' => array(
        'name' => 'Facebook',
        'url' => 'http://www.facebook.com/',
      ),
      'reddit' => array(
        'name' => 'Reddit',
        'url' => 'http://www.reddit.com/user/',
      ),
      'flickr' => array(
        'name' => 'Flickr',
        'url' => 'http://www.flickr.com/photos/',
      ),
      'googleplus' => array(
        'name' => 'Google+',
        'url' => 'http://plus.google.com/',
      ),
      'rss' => array(
        'name'=> 'Site Rss',
        'url' => $base_url . '/',
      ),
    );
    //@todo add admin structure to enter the desired ids for this array
    $config = array(
      'linkedin' => 'danielmcewan',
      'twitter' => 'mcewand',
      'github' => 'mcewand',
      'flickr' => 'danmcewan',
      'googleplus' => '104538832958282540813',
      'rss' => 'rss.xml',
      //'facebook' => 'dan.mcewan',
      //'reddit' => 'al_waqt',
    );
    $site_links = array();
    foreach ($options as $site => $elements) {
      if (isset($config[$site])) {
        $site_links[$site] = l('<img src="'. $base_url . '/' . drupal_get_path('module', 'follow_me') .'/images/'. $site . '.png" alt="'.$elements['name'] .'" />',
          $elements['url'] . $config[$site],
          array(
            'attributes' => array(
              'title' => 'Follow me on ' . $elements['name'],
              'target' => '_blank',
          ),
          'external' => TRUE,
          'html' => TRUE,
        ));
      }
    }

    //display config
    $style = 'display:inline';

    $args = array(
      'sites' => $site_links,
      'style' => $style,
    );
    $content = theme('follow_me_block', $args);
    $block = array(
      'subject' => '',
      'content' => $content,
    );
    return $block;
  }
}

/**
 * Implementation of hook_block_view();
 */
function follow_me_theme() {
  return array(
    'follow_me_block' => array(
      'variables' => array($args = NULL),
      'template' => 'follow-me-block',
    ),
  );
}

function follow_me_ctools_plugin_directory($owner, $plugin_type) {
  // We'll be nice and limit scandir() calls.
  if ($owner == 'ctools' && ($plugin_type == 'github'
    || $plugin_type == 'twitter')) {
    return 'plugins/' . $plugin_type;
  }
}
