$plugin = array(
  'title' => t('Follow Me: Twitter Connector'),
  'description' => t('Connect your Twitter Account'),
  'callback' => 'follow_me_twitter_ctools_access_check',
  'default' => array('field_age_value' => 0),
  'settings form' => 'follow_me_twitter_ctools_settings',
  'summary' => 'follow_me_twitter_ctools_summary',
);

function follow_me_twitter_ctools_access_check(){


}

function follow_me_twitter_ctools_settings(){


}

function follow_me_twitter_ctools_summary(){

}
